name: First Workflow

on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "hello world"
            - name: multiline command
              run: |
                node -v
                npm -v
    parallell-job:
        runs-on: macos-latest
        steps:
            - name: view sw version
              run: sw_vers
    dependent-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: echo a string
              run: Write-Output "windows string new"