name: Sample Action
on: [push]

jobs:
    sample-action:
        runs-on: ubuntu-latest
        steps:
            - name: Simple JS Action
              id: greet
              uses: actions/hello-world-javascript-action@master
              with:
                who-to-greet: 'Ali'
            - name: log greet time
              run: echo "${{ steps.greet.outputs.time }}"
